apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: rag-api
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: DEBUG
          value: "true"
        - name: ENABLE_PROFILING
          value: "true"