version: '3.8'

services:
  # RAG API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    env_file:
      - .env
    environment:
      CHROMA_PERSIST_DIR: /app/.chroma
      MLFLOW_TRACKING_URI: file:/mlflow
      PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus_multiproc
    volumes:
      - ./src:/app/src
      - ./api:/app/api
      - ./data:/app/data
      - ./.chroma:/app/.chroma
      - ./mlruns:/mlflow
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: rag-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - rag-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: rag-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - rag-network

  # MLflow Tracking Server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: rag-mlflow
    command: >
      mlflow server
      --backend-store-uri file:/mlflow
      --default-artifact-root /mlflow_artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlruns:/mlflow
      - mlflow_artifacts:/mlflow_artifacts
    ports:
      - "5000:5000"
    networks:
      - rag-network

volumes:
  prometheus_data:
  grafana_data:
  mlflow_artifacts:

networks:
  rag-network:
    driver: bridge