repos:
  - repo: local
    hooks:
      - id: uv-check
        name: UV Environment Check
        entry: uv run python -m pip check
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
        args: ["."]

      - id: ruff-lint
        name: Ruff Lint
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: false
        args: [".", "--fix"]

      - id: mypy
        name: MyPy Type Check
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["src", "api", "--ignore-missing-imports"]

      - id: pytest-fast
        name: Fast Tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        args: ["-m", "not integration", "--tb=short", "-v"]

      - id: ci-script
        name: Full CI Check
        entry: bash scripts/ci.sh
        language: system
        pass_filenames: false
        always_run: true
