apiVersion: v1
kind: Service
metadata:
  name: rag-api
  labels:
    app: rag-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api-metrics
  labels:
    app: rag-api
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics