apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api-green
  labels:
    app: rag-api
    version: green
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rag-api
      version: green
  template:
    metadata:
      labels:
        app: rag-api
        version: green
        component: backend
    spec:
      containers:
      - name: rag-api
        image: rag-pipeline:green
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: APP_VERSION
          value: "green"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: LLM_PROVIDER
          value: "stub"
        - name: PYTHONPATH
          value: "/app"
        envFrom:
        - configMapRef:
            name: rag-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api-green
  labels:
    app: rag-api
    version: green
spec:
  type: ClusterIP
  selector:
    app: rag-api
    version: green
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http