apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: rag-api
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: DEBUG
          value: "false"
        - name: ENABLE_PROFILING
          value: "false"
        - name: RATE_LIMIT_ENABLED
          value: "true"
        - name: RATE_LIMIT_REQUESTS_PER_MINUTE
          value: "100"