apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-production

bases:
- ../../base

namePrefix: prod-

patchesStrategicMerge:
- deployment-patch.yaml

configMapGenerator:
- name: rag-config
  behavior: merge
  literals:
  - APP_ENV=production
  - LOG_LEVEL=WARNING
  - MLFLOW_TRACKING_URI=http://mlflow-prod:5000
  - LLM_PROVIDER=openai

replicas:
- name: rag-api
  count: 5